import { v4 as uuidv4 } from 'uuid'

export const buildUser = (overrides = {}) => ({
  id: uuidv4(),
  email: `user_${Date.now()}@example.com`,
  name: 'Test User',
  phone: '+919876543210',
  password: '$2a$04$testHashedPasswordValueHere',
  role: 'CUSTOMER',
  isActive: true,
  isVerified: true,
  tokenVersion: 0,
  deletedAt: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})

export const buildRestaurant = (overrides = {}) => ({
  id: uuidv4(),
  ownerId: uuidv4(),
  name: 'Tasty Bites',
  slug: `tasty-bites-${uuidv4().substring(0, 8)}`,
  description: 'Delicious fast food & beverages',
  cuisineType: 'Indian, Fast Food',
  address: '123 MG Road, Indiranagar',
  city: 'Bengaluru',
  state: 'Karnataka',
  postalCode: '560038',
  latitude: 12.9716,
  longitude: 77.5946,
  phone: '+919876543211',
  email: 'info@tastybites.com',
  logoUrl: 'https://res.cloudinary.com/platemate/image/upload/logo.jpg',
  bannerUrl: 'https://res.cloudinary.com/platemate/image/upload/banner.jpg',
  isActive: true,
  isApproved: true,
  isOpen: true,
  averageRating: 4.5,
  totalReviews: 10,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})

export const buildMenuItem = (overrides = {}) => ({
  id: uuidv4(),
  restaurantId: uuidv4(),
  categoryId: uuidv4(),
  name: 'Paneer Butter Masala',
  description: 'Rich cottage cheese curry',
  price: 250,
  imageUrl: 'https://res.cloudinary.com/platemate/image/upload/paneer.jpg',
  isVeg: true,
  isAvailable: true,
  preparationTime: 20,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})

export const buildAddress = (overrides = {}) => ({
  id: uuidv4(),
  userId: uuidv4(),
  label: 'Home',
  street: '123 Main Street',
  landmark: 'Near Central Park',
  city: 'Bengaluru',
  state: 'Karnataka',
  postalCode: '560001',
  latitude: 12.9716,
  longitude: 77.5946,
  isDefault: true,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})

export const buildCartItem = (overrides = {}) => ({
  id: uuidv4(),
  cartId: uuidv4(),
  menuItemId: uuidv4(),
  quantity: 2,
  price: 250,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})

export const buildOrder = (overrides = {}) => ({
  id: uuidv4(),
  orderNumber: `PM-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-12345`,
  userId: uuidv4(),
  restaurantId: uuidv4(),
  deliveryRiderId: null,
  addressId: uuidv4(),
  status: 'PENDING',
  paymentStatus: 'PENDING',
  paymentMethod: 'ONLINE',
  subtotal: 500,
  taxFee: 25,
  deliveryFee: 40,
  discount: 50,
  grandTotal: 515,
  notes: 'Ring the doorbell',
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})

export const buildCoupon = (overrides = {}) => ({
  id: uuidv4(),
  code: 'WELCOME50',
  description: '50% off up to Rs 100',
  discountType: 'PERCENTAGE',
  discountValue: 50,
  minOrderValue: 200,
  maxDiscount: 100,
  expiresAt: new Date(Date.now() + 86400000 * 30),
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})
